name: hadolint

on:
  push:
    branches:
      - next
  pull_request:

jobs:
  hadolint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: brpaz/hadolint-action@v1.5.0
